def label = "docker-${UUID.randomUUID().toString()}"

podTemplate(label: label, yaml: """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:1.11
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
"""
  ) {

  def image = "jenkins/jnlp-slave"
  node(label) {
    stage('Build Docker image') {
      git 'https://github.com/lbpage/jenkins-docker.git'
      container('docker') {
        withCredentials([file(credentialsId: 'gcr-access', variable: 'FILE')]) {
          dir('/tmp/secrets/')
            sh 'use $FILE'
        //sh "echo $ | docker login -u _json_key --password-stdin https://gcr.io/active-alchemy-214615"
        //sh "docker build -t gcr.io/active-alchemy-214615/jenkins_test/${BUILD_ID} ."
        //sh "docker push  gcr.io/active-alchemy-214615/jenkins_test/${BUILD_ID}"
        }
      }
    }
  }
}