def label = "docker-${UUID.randomUUID().toString()}"
  
podTemplate(label: label, containers: [
  containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true),
  containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl:v1.8.8', command: 'cat', ttyEnabled: true),
  containerTemplate(name: 'helm', image: 'lachlanevenson/k8s-helm:latest', command: 'cat', ttyEnabled: true),
  containerTemplate(name: 'ssh', image: 'gotechnies/alpine-ssh:latest', command: 'cat', ttyEnabled: true)
],
volumes: [
  hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock')
]) 
  
  {

  def image = "jenkins/jnlp-slave"
  node(label) {
      stage('kubectl'){
        container('ssh'){
          withCredentials([sshUserPrivateKey(credentialsId: "gcp-cluster-ssh", keyFileVariable: 'keyfile')]) {
              sh "ssh -i ${keyfile} nix-store.nix-store.svc.cluster.local"
              sh "ls -al /nix"
          }   
        }
      }
  }
 
}